name: GitHub Metrics
on:
  schedule:
    - cron: "30 5 * * *"   # runs daily at 05:30 UTC
  workflow_dispatch:        # lets you run it manually

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics (public + private)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 10
          plugin_achievements: yes
          plugin_achievements_threshold: S
          plugin_achievements_display: compact
          config_timezone: Europe/Sofia
