name: GitHub Metrics
on:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics (languages only – clean baseline)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: header, repositories, metadata
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Europe/Sofia

          # Languages: deep, inclusive, ONLY "most-used"
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: 'most-used'     # ensure recently-used is OFF
          plugin_languages_recent_days: 0            # hard-disable recent activity path
          plugin_languages_recent_load: 0            # ^
          plugin_languages_limit: 50
          plugin_languages_threshold: 0%             # show tiny langs
          plugin_languages_categories: programming, markup, data
          plugin_languages_details: percentage, bytes-size, lines
